### ISSUE TITLE
undefined is not an object (evaluating 'navigation.state.params.navigatePress')

### ISSUE THREAD

**Issue by kala888** [SurpassRabbit/ReactNavigationDemo#1]
Steps:
1. Clone Code and install to IOS Siulator
2.Click the link "点我跳转到Detail1"
3.Click "我的" on Right Header
4.Got Error
![image](https://user-images.githubusercontent.com/1215976/28062509-c0c427d0-6660-11e7-9aa9-6615e79b8135.png)

**Comment by RabbitDream** [comment]
已经修复。
