### ISSUE TITLE
你好，想请教个问题，不知如何联系，所以写到这里，不是Issue。

### ISSUE THREAD

**Issue by kealuya** [SurpassRabbit/ReactNavigationDemo#2]
// 初始化StackNavigator
const MyNav = StackNavigator({
    // 将TabNavigator包裹在StackNavigator里面可以保证跳转页面的时候隐藏tabbar
    MyTab:{
        screen:MyTab,
    },
    // 将需要跳转的页面注册在这里，全局才可以跳转
    Detail1:{
        screen:Detail1
    },
    Detail2:{
        screen:Detail2,
    },

如果，MyTab的其中一个页面里，有很多个需要像Detail1,2这样需要不显示tabbar去跳转的页面，
都定义到这个主控件里吗？有没有别的办法呢？
随着开发，我会加入更多不显示tabbar的跳转，难道每次都要来这里修改吗？

像淘宝的app应用，也是bottom位置是tab，tab页面上有无数的不显示tabbar的跳转，我想用ReactNavigation达到那样的效果，只能像上面这样吗？
谢谢。

**Comment by RabbitDream** [comment]
加群 可以联系我呀。。

**Comment by RabbitDream** [comment]
只有定义过的才能跳转， 没办法像老路由那样控制
